Script started on 2016年03月02日 (週三) 22時19分33秒
]0;F74046080@2015cpp: ~[01;32mF74046080@2015cpp[00m:[01;34m~[00m$ [K]0;F74046080@2015cpp: ~[01;32mF74046080@2015cpp[00m:[01;34m~[00m$ whoami;pwd
F74046080
/home/F74046080
]0;F74046080@2015cpp: ~[01;32mF74046080@2015cpp[00m:[01;34m~[00m$  gitclonehttps://git hub.com/<your githubaccount>/lab1.git[A[10Pwhoami;pwd
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C gitclonehttps://githhub.com/<your githubaccount>/lab1.git[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgitclonehttps://githu[1P[A]0;F74046080@2015cpp: ~[01;32mF74046080@2015cpp[00m:[01;34m~[00m$ [C

bash: your: No such file or directory
]0;F74046080@2015cpp: ~[01;32mF74046080@2015cpp[00m:[01;34m~[00m$ gitclonehttps://githuub.com/<your githubaccount>/lab1.git[A[10Pwhoami;pwd
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgitclonehttps://githuub.com/<your githubaccount>/lab1.git[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C clonehttps://gith[1@u[A]0;F74046080@2015cpp: ~[01;32mF74046080@2015cpp[00m:[01;34m~[00m$ [C[C[C[C[C[C[C[C[C https://git[1@h[A]0;F74046080@2015cpp: ~[01;32mF74046080@2015cpp[00m:[01;34m~[00m$ [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gitF/lab1.git7/lab1.git4/lab1.git0/lab1.git4/lab1.git6/lab1.git0/lab1.git8/lab1.git0/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;F74046080@2015cpp: ~[01;32mF74046080@2015cpp[00m:[01;34m~[00m$ exit

Script done on 2016年03月02日 (週三) 22時29分03秒
